#ifndef _RETURN_CODES_H_
#define _RETURN_CODES_H_

#include <Arduino.h>

enum RETURN_CODES {RC_NONE=0, RC_ERROR=1, RC_WARN=2, RC_INFO=3, RC_DEBUG=4, RC_VERBOSE=5, RC_CMD_ECHO=6, RC_CMD_DONE=7, RC_DATA=8, RC_LOG=9, RC_STAIR_RESP=10, RC_VAR_VALUE=11};

enum ERROR_CODES {EC_NONE=0, EC_ABORT=1, EC_PARSE=2, EC_MAX_VARS=3, EC_VAR_DNE=4};


#endif //_RETURN_CODES_H_