
#ifndef _INTERFACE_TYPES_H_
#define _INTERFACE_TYPES_H_


#define DEFAULT_UINT_BITS 32
#define DEFAULT_INT_BITS 32
#define DEFAULT_BOOLEAN_ONE_BIT true

enum INTERFACE_TYPE {TYPE_UINT8, TYPE_UINT16, TYPE_UINT32, TYPE_UINT64, TYPE_INT8, TYPE_INT16, TYPE_INT32, TYPE_INT64, TYPE_FLOAT, TYPE_DOUBLE, TYPE_STRING, TYPE_BOOL};


#endif // _INTERFACE_TYPES_H_